// <auto-generated />
namespace EShop_IT2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataBaseChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataBaseChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202302101820570_DataBaseChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
